# Text Representation

1. What is feature extraction from text?

2. Why we need it?

3. Why it is so difficult?

4. What is the core idea?

5. Techniques using which we can implement the same?


Points:
 - See image is structured data since it has fixed rows and columns (resolution is fixed). But in case we are provied dataset where images are of different resolution then it would become unstructured one.
 - Similarly textual dataset is also unstructured. For eg: Sentence 1: I am good. Sentence 2: I am very good. We can clearly see that both the sentences are not having the same lenght. This is the reason why Textual dataset cannot be treated as the Strucuted dataset and is regarded as Unstructured data.
 - If out corpus size (Number of documnets or sentences) in textual dataset is small then we can apply one hot encoding. But in case we are provided with dataset with huge corpus then it won't be wise to do the same since, in that case we will be having a lot of unique words or vobaulary size will be huge. This will make embedding or numeric representation of tokenized word computational expensive. This is the reason why we avoid using the one hot encoding and use an another technique called BAG OF WORD(BOW).
 - BOW is suitable for sentiment analysis use case.

Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# BOW, N-grams, TFIDF are all word embedding techniques where we are basically representing words into numbers.

# Please note that all the word embedding techniques disscussed under this notebook is manual approach where we are counting the occurence of words in the sentence

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [3]:
#This is the library(CountVectorizer) needed for implementing BOW

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [6]:
bow.toarray()

#This will give BOW representation where each array's row represents respective bow numeric/vector representation
#for each sentence respectively

#This array has column titled with vocabulary in alphabetcal order. in the each number represents the count of
#that vocabulary in that sentence.
#array format [count of word 'comment', count of word 'dswithbappy', count of word 'people',
#                   count of word 'watch', count of word 'write']

#For Eg: Sentence 2 is: dswithbappy watch dswithbappy represents with array[1] = [0,2,0,1,0] where 2 means dswithbappy
#word occured 2 times in the sentence whereas 1 represents watch's occurence and 0 represents that other vobulary words
#are not present in the sentence.

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [8]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray() #here if we do not give toarray() then it will return sparse matrix
                                                    #object. To view encoded array use toarray()

array([[0, 1, 0, 1, 0]])

In [ ]:
X = bow.toarray()
y = df['output']

# Disadvantage with BOW:
Say we have huge vocabulary size. And in BOW we know that each enoded sentence have lenght equivalent to vocabulary lenght. So in such a case when we are encoding sentence with very small lenght then it will result in lot of 0s which will give sparse matrix. And when these 0s are huge then it can make model overfitted.

#  N-grams

N-grams is the extension of the BOW only.

In BOW we are are considering only 1 unique word at at time whose count/occurence we were measuring in the respective sentence(For better understanding see array[0] or array[1] in BOW example). But in N-grams technique we can set N=2,3.. so on where N represents the number of unique words that we can take at a time whose count/occurence we were measuring in the respective sentence.

In [9]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
# If N is set to 2 then BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

##Observe vocabulary is built considering unique combination of 2 words at a time for Bigrams. This in case of
##BOW was only one word at a time.

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

##since vocabulary is collection of 6 Bigrams, each array has the length of 6

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


# Advantage of using N-grams technique over BOW for sentiment analysis use case:

Sentence1: This is very good movie.

Sentence2: This is not very good movie.

For above 2 sentences using BOW will be able to capture sentiment of sentence by observing the presence of word not(single word at a time). One needs to see the contenxt as well. Like in which context not is being use. If we have few words before and after not then we would be able to correctly determine the sentiment of that respective word. Since in BOW at a time we can only consider only single word, there is no way we can observe the words before and after not. Therefore, possibility of BOW giving missleading sentiment is very high. 

Here, N-grams comes into rescue where we can capture or observe before and after word for not since vocabulary will be N-gramed. For eg: {'is not', 'not very'}. This will give better understanding of not being used in the sentence. Therefore, compared to BOW possibility of getting a missleading sentiment is very less.

In [10]:
#Tri grams

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [11]:
bow = cv.fit_transform(df['text'])

In [12]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

This calculates the most frequent occuring words and it will assign those words to a bigger number. This number is calculated based on the statistical equation(google to check that equation).

For example: This movie is amazing, amazing performance by SRK

Number of unique words = N = 7

This - 0.23 (Assigned very small number close to 0, since it's occurence in the sentence is only 1)

movie - 0.21 (Assigned very small number close to 0, since it's occurence in the sentence is only 1)

is - 0.20 (Assigned very small number close to 0, since it's occurence in the sentence is only 1)

amazing - 0.92 (Assigned large number close to 1, since it's occurence in the sentence is 2)

performance - 0.32

by - 0.33

SRK - 0.11

# Advantage of using TF-IDF over BOW and N-grams:

In BOW and N-grams we were getting a lot of 0s or sparse matrix which is prone to overfitting. Also, 0 plays no role in computation hence unecessary computtation cost is also inculded.

Whereas, in case of TF-IDF we are getting a value b/w 0 and 1 or in other words we are getting floating point numbers. There here the matrix obtained doesn't posses sparsity.

In [13]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [14]:
#TfidfVectorizer() used to implement the TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [15]:
arr = tfid.fit_transform(df['text']).toarray()

In [16]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [1]:
print(tfid.idf_)

# idf_ numbers are used in the statistical equation for the calculation of the number representation.
#Can skip this

NameError: name 'tfid' is not defined