In [ ]:
# We will be using Keras pythonic library for this implementation. So using below cmd we are verifying the same

!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.6
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

In [ ]:
from keras import Sequential  #Sequential used to create the Neural Network based models

In [ ]:

from keras.layers import Dense, SimpleRNN

In [ ]:
model=Sequential()

In [ ]:
model.add(SimpleRNN(4,input_shape=(4,5)))
#(4->Number of hidden layers, input_shape=(4->number of words in lengthiest sentence,5->Vocabulary))
#For exmaple if we have 3 sentence[movie was good, movie was bad, movie was not bad] so since 3rd sentence is lengthiest one
#with word count 4 we will use 4 as number of rows while defining the input_shape. While doing that for sentence 1 and 2
#(having word count=3) automatic padding of the 4th word will happen internally which probably will be encoded as 
#[0,0,0,0,0] representing no word

##Please note that above we have defined the hidden layer and using input_shape have define the input layer
##Also in above by default the activation function being used for the hidden layer neurons is tanh

model.add(Dense(1, activation="sigmoid")) #Here we have defined the Output layer with Sigmoid activation function
                                          #being used for binary classification

In [ ]:
#VVImp

model.summary()

##Number of neurons at input layer = Vocabulary size
##We have 4 words in a sentence (where 2 sentences were padded to 4 length as explained above). So 4 timestamp is required 
##to pass a sentence and generated predicted output. When it goes to next word there is a reset and again same chain goes on
##Or in other words feeback is going to terminate only when all the words a sentence is completely processed through RNN

##Trainable params = 5*4+4 +  4*4 +   4*1+1 = 
##                    I/P    Hidden  O/P   

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 4)                 40        
                                                                 
 dense_1 (Dense)             (None, 1)                 5         
                                                                 
Total params: 45 (180.00 Byte)
Trainable params: 45 (180.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

##These are internally assigned weights. each array represents a weight/bias. Below we are getting 5 weights/bias.
##lets decode each of them:

##model.get_weights()[0] and model.get_weights()[1] are decoded in the below cells

#model.get_weights()[2] or array([0., 0., 0., 0.], dtype=float32), represents the bias for the b/w I/P and hidden layer
##Note that bias is not need in feedback loop only weight is required there

##model.get_weights()[3], represents the weights b/w hidden and output layer

##model.get_weights()[4] or rray([0.] represents the bias b/w hidden and output layer

[array([[-0.6955212 ,  0.7785003 , -0.07227027, -0.69514155],
        [-0.14051485,  0.78357303,  0.79060864, -0.26040286],
        [-0.16312689, -0.8125834 , -0.21167338,  0.58308876],
        [ 0.34405172, -0.22713137, -0.7825148 , -0.13567638],
        [-0.1023249 ,  0.6525897 , -0.53951585,  0.7725153 ]],
       dtype=float32),
 array([[ 0.4514761 , -0.7264177 , -0.4277959 , -0.29236478],
        [-0.8617577 , -0.5050725 , -0.04722452, -0.00672787],
        [-0.21230304,  0.40662986, -0.3590341 , -0.8128186 ],
        [ 0.0920344 , -0.22775255,  0.8281636 , -0.5037891 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.25142407],
        [ 0.8916596 ],
        [ 0.4443779 ],
        [-0.7056412 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.get_weights()[0]  ##These are the connecting weights b/w I/P and hidden layer

array([[-0.6955212 ,  0.7785003 , -0.07227027, -0.69514155],
       [-0.14051485,  0.78357303,  0.79060864, -0.26040286],
       [-0.16312689, -0.8125834 , -0.21167338,  0.58308876],
       [ 0.34405172, -0.22713137, -0.7825148 , -0.13567638],
       [-0.1023249 ,  0.6525897 , -0.53951585,  0.7725153 ]],
      dtype=float32)

In [ ]:
model.get_weights()[0].shape #We have 5 neurons in I/P and 4 hidden neurons that why above we can see we have 20 possible
                             #weights in the first section of the network

(5, 4)

In [ ]:
model.get_weights()[1]  ##This section represents the feedback loop. 

array([[ 0.4514761 , -0.7264177 , -0.4277959 , -0.29236478],
       [-0.8617577 , -0.5050725 , -0.04722452, -0.00672787],
       [-0.21230304,  0.40662986, -0.3590341 , -0.8128186 ],
       [ 0.0920344 , -0.22775255,  0.8281636 , -0.5037891 ]],
      dtype=float32)

In [ ]:
model.get_weights()[1].shape  #There are 4 hidden neurons and each passes output to each other which is govered through
                              #some trainable weights. That's why we are having 20 possible weight combinations


(4, 4)

In [ ]:
from keras.datasets import imdb 
#We are going to use this inbuilt dataset which is judges the sentiment of reviews for movies

In [ ]:

(X_train,y_train),(X_test,y_test)=imdb.load_data()
    
##If we are going to print imdb.load_data() then we will find out that this is already an encoded dataset which is in tuple
##form. So, order to unpack this tuple dataset we are writing like this which is set format from keras side
# (X_train,y_train),(X_test,y_test) format and in tuple form

In [ ]:
len(X_train[0])  ##representing that there are 218 words which are already encoded in the first review in train split

#To view this simply use print(X_train[0])
#Please note embedding here used doesn't seem like one hot encoding. Instead it's some different encoding is used which
#is done using keras tokenizer(google it). 

218

In [ ]:
len(X_train[1])  ##representing that there are 189 words which are already encoded in the second review in train split

189

In [ ]:
len(X_train[2])

141

In [ ]:
mylist=[]
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

In [ ]:
X_train.shape   #Representing that there are 25000 training data

(25000,)

In [ ]:
X_test.shape    #Representing that there are 25000 test data

(25000,)

In [ ]:
import numpy as np
sent=[

      "india won worldcup",
      "rohit played very well",
      "above all is my imagination",
      "bharat mata ki jay",
      "definatly we goona win next worldcup"
]  ##In case sentences are untokenized or unembedded words, then by using kereas tokenizer we will first tokenize them.
  ##In imdb dataset this was already done, that's why took this example to explain how tokenisation be done

In [ ]:
sent

['india won worldcup',
 'rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'definatly we goona win next worldcup']

In [ ]:
# it is performing integer encoding
from keras.preprocessing.text import Tokenizer

In [ ]:

tokenizer=Tokenizer()

In [ ]:
tokenizer.fit_on_texts(sent)

In [ ]:
tokenizer.word_index

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definatly': 17,
 'we': 18,
 'goona': 19,
 'win': 20,
 'next': 21}

In [ ]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definatly', 1),
             ('we', 1),
             ('goona', 1),
             ('win', 1),
             ('next', 1)])

In [ ]:
tokenizer.document_count  ##Document_count represents the number of sentences

5

In [ ]:
encoding=tokenizer.texts_to_sequences(sent)   ##self explanatory from the execution of the below cell

In [ ]:
encoding

[[2, 3, 1],
 [4, 5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21, 1]]

In [ ]:
##In above we can see that that each encoded document or sentence is of different length which we have to convert into same
##length. That's we are we are using padding by importing following pyhtonic library

from keras.utils import pad_sequences

In [ ]:

pad_sequences(encoding ,padding="post")

##By default padding is set to "pre" which will do the pre padding whereas 0s will appear at the begning.
#But we want them to appear at end that why padding is set to "post"

##Also, we can observe that here by default padding is done according to the length of longest sentence

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

In [ ]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [ ]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
##VVImp

##Why doing padding here. So we learned that by default padding is done according to the lengthiest word. But in real time
##scenario that can be many words in the lenthiest sentence say for example len(X_train[0]) is 218. So if we start padding
##words upto max length 218 then it would be very much computational expensive.

##So in such a case we can go with the padding equivalent to the length of the sentence having smallest word count.
##In above cell (17th cell above starting from this cell) we have written a logic to capture the review with smallest word
##count which is only 11. So here in this case if we taken max length padding as 11 then a lot of contenxual information
##will get miss out. So that why we are taking maxlen padding somewhere in b/w that is 50. We might loss contexual
##understanding but this will speed up the training process of our RNN model

X_train=pad_sequences(X_train ,padding="post",maxlen=50)

In [ ]:

X_test=pad_sequences(X_test ,padding="post",maxlen=50)

In [ ]:
model=Sequential()

In [ ]:

model.add(SimpleRNN(32,input_shape=(50,1)))   #Decode this by own self as explained earlier

In [ ]:
model.add(Dense(1,activation="sigmoid"))

In [ ]:

model.summary()

##Decode the trainable params by own self as explained earlier

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 39s 42ms/step - loss: 0.6939 - accuracy: 0.5092 - val_loss: 0.6945 - val_accuracy: 0.5080
Epoch 2/5
782/782 [==============================] - 34s 44ms/step - loss: 0.6932 - accuracy: 0.5061 - val_loss: 0.6939 - val_accuracy: 0.5069
Epoch 3/5
782/782 [==============================] - 32s 41ms/step - loss: 0.6931 - accuracy: 0.5100 - val_loss: 0.6942 - val_accuracy: 0.5024
Epoch 4/5
782/782 [==============================] - 31s 40ms/step - loss: 0.6929 - accuracy: 0.5080 - val_loss: 0.6965 - val_accuracy: 0.5026
Epoch 5/5
782/782 [==============================] - 32s 42ms/step - loss: 0.6929 - accuracy: 0.5100 - val_loss: 0.6944 - val_accuracy: 0.5039


In [ ]:
model.predict(X_test)

782/782 [==============================] - 5s 7ms/step


array([[0.5120173],
       [0.5120173],
       [0.5120173],
       ...,
       [0.5120173],
       [0.512018 ],
       [0.5120173]], dtype=float32)

In [ ]:

loss,accuracy=model.evaluate(X_test,y_test)

782/782 [==============================] - 7s 9ms/step - loss: 0.6944 - accuracy: 0.5039


In [ ]:
loss

0.6943767070770264

In [ ]:
accuracy

0.5038800239562988